### ISSUE TITLE
Login: after a page reload authenticated users get logged out

### ISSUE THREAD

**Issue by RAeschimann** [uenala/project_spa_bergauf#47]

**Comment by uenala** [comment]
It might seem like they are logged out, but actually users are still logged in technically (see globals cookie) after a page reload. I suspect the problem is located somewhere in the logged-in-check in index.html.

**Comment by uenala** [comment]
The "problem" was a known behaviour of $rootScope, values in $rootScope are cleared during page-refresh. Solution: read back "globals" cookie-value and re-set values in $rootScope.
