### ISSUE TITLE
Errorhandling for missing thumbnails in gallery-*-directive

### ISSUE THREAD

**Issue by RAeschimann** [uenala/project_spa_bergauf#70]
GET .../%7B%7BserverUrl.data%7D%7D%7B%7BgalleryObj.icon%7D%7D 404 (Not Found)

Where does this request to a gallery came from?

Problem is only reproducable after a user login.

**Comment by uenala** [comment]
Possible source of problem:
app/home/directives/gallery-thumbnail-directive.tpl.html,
Line number # 4   `..<img class="lazy media-object" data-original="{{serverUrl.data}}{{galleryObj.icon}}" alt="" height="120" width="160" />..`

**Comment by RAeschimann** [comment]
Create a check-image directive like http://www.ngroutes.com/questions/1b08552/angularjs-display-default-image-if-original-does-not-exists.html
